### ISSUE TITLE
New cat time tracker

### ISSUE THREAD

**Issue by HsuTing** [HsuTing/cat-time-tracker#6]
# Website
- [x] Can use time tracker
- [x] Add `github` link
- [x] Can modify `Todo`

**Comment by HsuTing** [comment]
Todo in Time tracker should be not done.

**Comment by HsuTing** [comment]
[Can add `Todo`](https://github.com/HsuTing/cat-time-tracker/commit/072aa630961a48bccd3e93f5e95ebea663169fcb)
